// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXfZmlrnZJzzDvaWdBVBWaTJZ7_6VlCI',
    appId: '1:854797702565:web:0f56dd1ea9d788f177844c',
    messagingSenderId: '854797702565',
    projectId: 'flutter-udemy-e155b',
    authDomain: 'flutter-udemy-e155b.firebaseapp.com',
    storageBucket: 'flutter-udemy-e155b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC7UMSJp1lBG0AxSuct-8n68Rs9x8Y_Pw',
    appId: '1:854797702565:android:c0519549be90fad577844c',
    messagingSenderId: '854797702565',
    projectId: 'flutter-udemy-e155b',
    storageBucket: 'flutter-udemy-e155b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7FbSuXh9QhIhGQj7jWtCXVeuXUkdLg0',
    appId: '1:854797702565:ios:fd79f53ae0383b9a77844c',
    messagingSenderId: '854797702565',
    projectId: 'flutter-udemy-e155b',
    storageBucket: 'flutter-udemy-e155b.appspot.com',
    iosClientId: '854797702565-b3ieb1j8u57kb22uafk02njs8cdf0usa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUdemySns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7FbSuXh9QhIhGQj7jWtCXVeuXUkdLg0',
    appId: '1:854797702565:ios:672794880287db3977844c',
    messagingSenderId: '854797702565',
    projectId: 'flutter-udemy-e155b',
    storageBucket: 'flutter-udemy-e155b.appspot.com',
    iosClientId: '854797702565-h3bg6i78kovv7bhdg3kohff8deis0ath.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUdemySns.RunnerTests',
  );
}
